# Generated by Django 5.0.3 on 2024-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='authorization',
            field=models.CharField(unique=True),
        ),
    ]
